"""Deterministic replay of recorded event files, as if they were live.

Reads the gzip JSON-lines files the recorder writes (one per instrument per
day) and delivers the events merged in arrival order. The order is a pure
function of the files: (arrival time, file name, line number), so the same
files always give the same stream and therefore the same features, signals
and decisions.

Two speeds:

* ``asap``      - as fast as the engine can take them (research, tests).
* ``realtime``  - paced by the recorded arrival times (``speed`` = 2.0 plays
  twice as fast), to watch a recorded session as if it were happening.

Time is VIRTUAL in both: the engine's clock is the arrival time of the last
event delivered, never the wall clock, which is what makes a replay
reproducible.
"""
from __future__ import annotations

import datetime as dt
import gzip
import heapq
import json
import time
from pathlib import Path
from typing import Callable, Iterator, Optional, Sequence

from .. import INSTITUTIONAL
from ..book import Event, from_dict, received_at
from .base import DOWN, FINISHED, LIVE, FeedAdapter, FeedHealth


def find_files(paths: Sequence[str | Path] | str | Path) -> list[Path]:
    """Files from a list of files and/or directories (searched recursively)."""
    if isinstance(paths, (str, Path)):
        paths = [paths]
    out: list[Path] = []
    for p in paths:
        p = Path(p)
        if p.is_dir():
            out.extend(sorted(p.rglob("*.jsonl.gz")))
            out.extend(sorted(p.rglob("*.jsonl")))
        elif p.exists():
            out.append(p)
    return sorted(set(out))


def _read(path: Path, idx: int) -> Iterator[tuple]:
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8") as fh:
        for n, line in enumerate(fh):
            line = line.strip()
            if not line:
                continue
            ev = from_dict(json.loads(line))
            yield (received_at(ev), idx, n, ev)


CHANNEL_SEQUENCED = {"databento"}        # event sources whose sequence numbers are per channel, not per instrument


class ReplayFeed(FeedAdapter):
    vendor = "replay"
    virtual_time = True
    sequence_scope = "instrument"

    def __init__(self, paths, speed: str | float = "asap", instruments: Optional[Sequence[str]] = None,
                 wall_clock: Callable[[], float] = time.monotonic, synthetic: Optional[bool] = None):
        self.files = find_files(paths)
        self.speed = speed
        self.factor = 1.0 if speed in ("realtime", "real-time") else (float(speed) if not isinstance(speed, str) else 0.0)
        self.only = set(instruments) if instruments else None
        self.wall_clock = wall_clock
        self._it: Optional[Iterator] = None
        self._pending: Optional[Event] = None
        self._count = 0
        self._last: Optional[dt.datetime] = None
        self._first: Optional[dt.datetime] = None
        self._wall0: Optional[float] = None
        self._done = False
        self._error = ""
        self._connected = False
        # a recording made from the synthetic generator is still synthetic
        self.synthetic = bool(synthetic) if synthetic is not None else any("synthetic" in str(f).lower() for f in self.files)

    def connect(self) -> bool:
        if not self.files:
            self._error = "no recording files found"
            return False
        try:
            streams = [_read(f, i) for i, f in enumerate(self.files)]
            self._it = heapq.merge(*streams, key=lambda x: (x[0], x[1], x[2]))
            self._connected = True
            self._done = False
            # events generated by the synthetic scenarios carry source "synthetic": a recording of them stays
            # SYNTHETIC whatever its file is called
            first = self._next()
            self.sequence_scope = type(self).sequence_scope
            if first is not None:
                self._pending = first
                src = str(getattr(first, "source", "")).lower()
                if src == "synthetic":
                    self.synthetic = True
                # the sequence numbers mean what they meant live: a recording of a feed that numbers
                # per CHANNEL (Databento/CME) is checked per channel, as it was when it ran
                if src in CHANNEL_SEQUENCED:
                    self.sequence_scope = "channel"
            return True
        except Exception as exc:
            self._error = f"{type(exc).__name__}: {exc}"
            return False

    def subscribe(self, instruments: Sequence[str]) -> None:
        if instruments:
            self.only = set(instruments) | {""}

    def _next(self) -> Optional[Event]:
        if self._pending is not None:
            ev, self._pending = self._pending, None
            return ev
        if self._it is None:
            return None
        while True:
            try:
                item = next(self._it)
            except StopIteration:
                self._done = True
                return None
            except Exception as exc:
                self._error = f"{type(exc).__name__}: {exc}"
                self._done = True
                return None
            ev = item[3]
            if self.only is None or ev.instrument in self.only:
                return ev

    def events(self, max_events: int = 10_000) -> list[Event]:
        out: list[Event] = []
        if not self._connected or (self._done and self._pending is None):
            return out
        while len(out) < max(1, int(max_events)):
            ev = self._next()
            if ev is None:
                break
            t = received_at(ev)
            if self.factor > 0:
                if self._first is None:
                    self._first, self._wall0 = t, self.wall_clock()
                due = (t - self._first).total_seconds() / self.factor
                if self.wall_clock() - self._wall0 < due:
                    self._pending = ev                  # not yet: hold it for the next call
                    break
            out.append(ev)
            self._count += 1
            self._last = t
        return out

    def now(self) -> Optional[dt.datetime]:
        return self._last

    def exhausted(self) -> bool:
        return self._done and self._pending is None

    def health(self) -> FeedHealth:
        if self._error and not self._connected:
            return FeedHealth(DOWN, f"replay cannot start: {self._error}", self.vendor, INSTITUTIONAL, self.synthetic)
        state = FINISHED if self.exhausted() else LIVE
        reason = (f"replay of {len(self.files)} recorded file(s) finished" if state == FINISHED
                  else f"replaying {len(self.files)} recorded file(s) ({self.speed})")
        return FeedHealth(state, reason, self.vendor, INSTITUTIONAL, self.synthetic, self._connected, self._count,
                          self._last.isoformat() if self._last else None, self._error)

    def recover(self, reason: str = "") -> bool:
        return True                                     # a recording cannot be re-requested; it is what it is
