(() => {
  'use strict';
  const M=window.FRETWISE_MUSIC,A=window.FRETWISE_AUDIO;
  const el=(id)=>document.getElementById(id);
  const DEFAULT={capo:5,tempo:86,lesson:'capo',prefs:{explanation:'short',pace:'gentle',autoHints:true,speak:true},stats:{sessions:0,demos:0,questions:0},knowledge:[
    'Advanced beginner: knows Am, E, Em, D, Dm, Fmaj7, C; working on G and A.',
    'Barre chords and finger stretching are challenging. Offer manageable steps and a guitar setup check.',
    'Working towards Sultans of Swing with a capo, often fret 3 or 5.',
    'Can feel overwhelmed by complex teaching. Start with one short instruction and a demonstration.'
  ],changes:[],imageData:null,importedLessons:[],messages:[]};
  const KEY='fretwise-prototype-v01';let stored={};try{stored=JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){}
  const state={...DEFAULT,...stored,prefs:{...DEFAULT.prefs,...(stored.prefs||{})},stats:{...DEFAULT.stats,...(stored.stats||{})}};
  state.stats.sessions++;
  let currentStep=0, demoRunning=false, demoTimers=[], backingOn=false, recognition=null, builderRecognition=null, missed=0, lastDetected='', lastPitchAt=0, lastSuccess='', spokenNotice=false;
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){console.warn('Local storage full',e);}}
  const lessons=()=>[...M.LESSONS,...state.importedLessons];
  const lesson=()=>lessons().find(x=>x.id===state.lesson)||M.LESSONS[0];
  function selectOptions(){const sel=el('exerciseSelect');sel.innerHTML='';for(const item of lessons()){const opt=document.createElement('option');opt.value=item.id;opt.textContent=item.name;sel.append(opt);}sel.value=state.lesson;}
  function initWood(){const wood=el('teacherFrets');wood.innerHTML='';for(let i=1;i<=5;i++){const fret=document.createElement('div');fret.className='fret-segment';fret.dataset.fret=String(i);wood.append(fret);}for(let i=0;i<6;i++){const line=document.createElement('span');line.className='string-line';line.style.top=(((i+.5)/6)*100)+'%';el('teacherNeck').append(line);}let barre=document.createElement('div');barre.className='hand-barre';barre.id='handBarre';el('teacherHand').append(barre);}
  function refreshInlayMarkers(){document.querySelectorAll('.fret-segment').forEach(segment=>{segment.querySelectorAll('.fret-marker').forEach(marker=>marker.remove());const physical=Number(segment.dataset.fret)+state.capo;if([3,5,7,9,12,15,17].includes(physical)){const marker=document.createElement('span');marker.className='fret-marker';segment.append(marker);if(physical===12){const second=marker.cloneNode();second.style.top='34%';marker.style.top='66%';segment.append(second);}}});}
  function humanShape(step){return step.chord?(M.CHORDS[step.chord]?.name||step.chord):(step.label||'Single note');}
  function stepInfo(step){if(step.chord)return 'Sounds as '+M.chordSound(step.chord,state.capo)+(state.capo?' with capo '+state.capo:' without capo');const notes=M.stepMidis(step,state.capo);return notes.length?M.midiToName(notes[0])+' sounding · string '+(6-step.string)+' · fret '+step.fret:'Practice note';}
  function renderHand(step){const frets=M.stepFrets(step),fingers=M.stepFingers(step);for(let n=1;n<=4;n++){const node=document.querySelector('.finger-'+n);node.style.display='none';}const hasBarre=step.chord==='Fmini'||step.chord==='F';const barre=el('handBarre');barre.style.display='none';if(hasBarre){barre.style.display='block';barre.style.left='10%';barre.style.top=step.chord==='F'?'50%':'24%';barre.style.height=step.chord==='F'?'92%':'26%';}const taken=new Set();frets.forEach((f,i)=>{const finger=fingers[i];if(f<1||f>5||!finger||taken.has(finger)||(finger===1&&hasBarre))return;taken.add(finger);const node=document.querySelector('.finger-'+finger);node.style.display='block';node.style.left=((f-.5)/5*100)+'%';node.style.top=(((5-i)+.5)/6*100)+'%';});const palm=el('teacherHand').querySelector('.hand-palm');const played=frets.filter(x=>x>0);const centre=played.length?played.reduce((a,b)=>a+b,0)/played.length:2;palm.style.left=Math.min(60,Math.max(12,(centre-.5)/5*100-6))+'%';}
  function renderStage(){refreshInlayMarkers();const l=lesson(),step=l.steps[Math.min(currentStep,l.steps.length-1)];el('exerciseTitle').textContent=l.title;el('nowChord').textContent=humanShape(step);el('actualChord').textContent=stepInfo(step);renderHand(step);renderSteps();if(!el('hintPanel').classList.contains('hidden'))renderHint();el('profileCapo').textContent=state.capo?'Fret '+state.capo:'None';}
  function renderSteps(){const box=el('stepsTrack');box.innerHTML='';lesson().steps.forEach((step,i)=>{const button=document.createElement('button');button.className='step-card'+(i===currentStep?' active':'');button.innerHTML='<strong>'+(i+1)+'</strong><small></small>';button.querySelector('small').textContent=step.label||humanShape(step);button.title='Select phrase '+(i+1);button.addEventListener('click',()=>{stopDemo();currentStep=i;renderStage();tutor('Got it. Phrase '+(i+1)+' selected. Press Hear & watch and I’ll demonstrate from here.');});box.append(button);});}
  function renderHint(){const step=lesson().steps[currentStep], frets=M.stepFrets(step),fingers=M.stepFingers(step);el('hintTitle').textContent=humanShape(step)+' · finger-by-finger';el('hintText').textContent=step.chord?'Green circles show where fingers go. Read the top row as the thin, high e string. Numbers are your fingers (1=index, 4=little finger). Press just behind each fret, not on the metal.':'The green circle is your target note. Try that one string slowly before playing the full phrase.';const box=el('miniFret');box.innerHTML='';const names=['e','B','G','D','A','E'];for(let row=0;row<6;row++){const label=document.createElement('span');label.className='mini-cell label';label.textContent=names[row];box.append(label);for(let fret=1;fret<=5;fret++){const cell=document.createElement('span');cell.className='mini-cell';const idx=5-row;if(frets[idx]===fret){const dot=document.createElement('span');dot.className='dot';dot.textContent=fingers[idx]||'●';cell.append(dot);}box.append(cell);}}}
  function showHints(trigger){el('hintPanel').classList.remove('hidden');el('showHints').textContent='✓ Hide fret help';renderHint();if(trigger==='auto')tutor('We’ve hit a tricky spot a few times. I’ve opened the extra finger-position guide. Just focus on one note at a time.');}
  function hideHints(){el('hintPanel').classList.add('hidden');el('showHints').textContent='◎ Show fret help';}
  function updateStats(){el('statSessions').textContent=state.stats.sessions;el('statDemos').textContent=state.stats.demos;el('statQuestions').textContent=state.stats.questions;}
  function stopDemo(){demoTimers.forEach(clearTimeout);demoTimers=[];demoRunning=false;A.stopAllNotes();el('playDemo').innerHTML='▶ <span>Hear & watch</span>';el('teacherNeck').closest('.guitar-demo').classList.remove('is-playing');if(el('backingWithDemo').checked&&backingOn)toggleBacking(false);}
  function queue(fn,delay){demoTimers.push(setTimeout(fn,delay));}
  function playDemo(){stopDemo();let audio;try{audio=A.ensure();}catch(e){tutor(e.message);return;}const l=lesson(),duration=(60/state.tempo)*1000*(l.kind==='melody'?1:4),start=currentStep;demoRunning=true;state.stats.demos++;save();updateStats();el('playDemo').innerHTML='◉ <span>Demonstrating...</span>';el('teacherNeck').closest('.guitar-demo').classList.add('is-playing');if(el('backingWithDemo').checked)toggleBacking(true);for(let i=start;i<l.steps.length;i++){const ix=i;queue(()=>{currentStep=ix;renderStage();const step=l.steps[ix];if(l.kind==='melody')A.guitar(M.stepMidis(step,state.capo)[0],audio.currentTime+.02,.34);else A.chord(step,state.capo,audio.currentTime+.02,.20);},(i-start)*duration);}queue(()=>{stopDemo();currentStep=start;renderStage();},(l.steps.length-start)*duration+180);}
  function toggleBacking(force){const shouldStart=typeof force==='boolean'?force:!backingOn;if(shouldStart){try{A.startBacking(()=>({tempo:state.tempo,capo:state.capo,lesson:lesson(),drums:el('trackDrums').checked,bass:el('trackBass').checked,rhythm:el('trackRhythm').checked}));backingOn=true;el('backingToggle').textContent='■ Stop backing band';}catch(e){tutor(e.message);}}else{A.stopBacking();backingOn=false;el('backingToggle').textContent='▶ Start backing band';}}
  function speak(text){if(!state.prefs.speak||!window.speechSynthesis)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text.replace(/\*+/g,'').slice(0,650));u.rate=.98;u.pitch=1.06;u.lang='en-GB';speechSynthesis.speak(u);}catch(e){console.warn(e);}}
  function addBubble(kind,text,record=true){const container=el('conversation');const wrapper=document.createElement('div');wrapper.className='bubble '+kind;const meta=document.createElement('div');meta.className='bubble-meta';meta.textContent=kind==='tutor'?'FRET · YOUR GUITAR COACH':'YOU';wrapper.append(meta);const content=document.createElement('div');content.textContent=text;wrapper.append(content);container.append(wrapper);container.scrollTop=container.scrollHeight;if(record){state.messages.push({kind,text,time:new Date().toISOString()});state.messages=state.messages.slice(-35);save();}}
  function tutor(text){addBubble('tutor',text);speak(text);}
  function remember(sentence){if(!state.knowledge.includes(sentence)){state.knowledge.push(sentence);state.knowledge=state.knowledge.slice(-18);}save();renderMemory();}
  function respondTo(msg){const q=msg.toLowerCase();if(/too much|overwhelm|confus|one step|simple|shorter|one ear|slow explanation|too fast explaining/.test(q)){state.prefs.explanation='short';state.prefs.pace='gentle';remember('Prefer just one short instruction, followed by a demonstration and time to try.');renderPrefs();return 'Got it. I was giving you too much at once. From now on: one small instruction, then you try. Would you like me to demonstrate the current shape?';}
    if(/barre|bar chord|bar chord|finger(s)? (don't|do not|won't|cannot|can't) stretch|press down|hands? (hurt|ache)/.test(q)){remember('When barre chords are difficult, start with easy partial F shapes and check comfort and string action.');state.lesson='barre';currentStep=0;selectOptions();renderStage();return 'Let’s make F much easier. Start with Fmaj7, which you already know. Then we’ll play the small three-string F, without a full barre. If pressing strings hurts, stop and we’ll look at your hand position or guitar setup. One step at a time.';}
    if(/(show|need|give).*(dot|fret|finger|diagram)|where.*finger/.test(q)){showHints();return 'I’ve opened the extra fretboard guide. The green dots show finger positions. We’ll leave it here until you no longer need it.';}
    if(/hide.*(dot|fret|finger|diagram)|stop.*(dot|hint)/.test(q)){hideHints();return 'Done. Back to watching the teacher’s hands on the guitar.';}
    if(/(again|repeat|play.*(part|phrase|section|lick)|show me|demonstrat)/.test(q)){playDemo();return 'I’m demonstrating from the selected phrase. Watch my fretting hand and listen to the notes.';}
    if(/(stop|pause) (play|music|sound|demo)/.test(q)){stopDemo();toggleBacking(false);return 'Stopped. Tell me exactly which bit you want help with.';}
    if(/slower|slow down/.test(q)){state.tempo=Math.max(55,state.tempo-12);renderTempo();save();return 'Slowed it down to '+state.tempo+' beats per minute. Try that speed.';}
    if(/faster|speed up/.test(q)){state.tempo=Math.min(140,state.tempo+10);renderTempo();save();return 'We’re now at '+state.tempo+' beats per minute. Go at your own pace.';}
    if(/learn.*(sultans|dire straits)|sultans of swing/.test(q))return 'We can use Sultans of Swing as your main goal. I have your capo settings saved, but I won’t pretend I have an accurate song transcription or recording yet. For now we can practise chord shapes and import an arrangement you have permission to use.';
    if(/teach.*(style|way|method)|you.*(teach|explain)|your method/.test(q)){remember('Learner gives specific verbal feedback on teaching method; respect it and adapt future instructions.');return 'I’m listening. Tell me exactly what part of my teaching isn’t working. I can make instructions shorter, demonstrate first, or change the exercise. I’ll remember what helps you.';}
    if(/(change|edit|add|build).*(app|software|button|screen|feature)/.test(q)){goPage('builder');return 'Sounds like an app improvement. I’ve opened Owner Mode so we can save a change request for Claude Code, rather than confuse it with a lesson preference.';}
    if(/(hello|hi|hey)/.test(q))return 'Hi! We can pick up your chord changes, work on that F shape, or learn a new little lick. What sounds good?';
    return state.prefs.explanation==='short'?'I hear you. Let’s tackle just one thing. Could you tell me which chord, note or movement is hardest right now? I’ll demonstrate it first.':'Tell me a little more about the exact point where you get stuck. We can slow it down, demonstrate the finger positions and practise one phrase at a time.';
  }
  function message(text){if(!text.trim())return;addBubble('user',text.trim());state.stats.questions++;updateStats();el('messageInput').value='';const response=respondTo(text.trim());tutor(response);save();}
  function renderPrefs(){el('explanationLength').value=state.prefs.explanation;el('teachingPace').value=state.prefs.pace;el('autoHints').checked=state.prefs.autoHints;el('speakReplies').checked=state.prefs.speak;el('voiceToggle').textContent=state.prefs.speak?'◖))':'◖×';}
  function renderMemory(){const list=el('memoryList');list.innerHTML='';state.knowledge.forEach(v=>{const div=document.createElement('div');div.className='memory-item';div.textContent=v;list.append(div);});}
  function renderTempo(){el('tempoRange').value=state.tempo;el('tempoLabel').textContent=state.tempo+' BPM';}
  function goPage(id){document.querySelectorAll('.page').forEach(node=>node.classList.toggle('active',node.id==='page-'+id));document.querySelectorAll('.nav-link').forEach(node=>node.classList.toggle('active',node.dataset.page===id));const names={studio:'Practice studio',teacher:'Your tutor',guitar:'My guitar',progress:'My progress',builder:'Change the app'};el('breadcrumb').textContent=names[id]||id;window.location.hash=id;}
  function exportJSON(name,data){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function renderChanges(){const box=el('changeHistory');box.innerHTML='';if(!state.changes.length){box.textContent='No change requests saved yet.';box.className='change-history note';return;}box.className='change-history';state.changes.slice().reverse().forEach((request,i)=>{const div=document.createElement('div');div.className='change-item';div.textContent=request.text;const meta=document.createElement('small');meta.textContent='Saved '+new Date(request.date).toLocaleString('en-GB')+' · Ready for code review';div.append(meta);box.append(div);});}
  function changeBrief(){return `You are the coding agent for Fretwise, a local-first prototype AI guitar tutor. Implement the following owner-requested changes safely and incrementally. Preserve current working features and tests. Never insert API secrets into client code. Avoid copyrighted song reproductions unless valid rights are confirmed. The virtual guitar hand demonstration is the DEFAULT; extra fretboard dots appear only on learner request or after repeated difficulty. Never claim pitch-only mic analysis proves a chord was played correctly. New changes should be previewable, tested, and reversible.\n\nOWNER REQUESTS:\n${state.changes.map((c,i)=>`${i+1}. ${c.text}`).join('\n')||'(None saved.)'}\n\nUSER LEARNING PREFERENCES:\n${JSON.stringify(state.prefs,null,2)}\n\nDeliver: scope, file changes, runnable tests, accessibility check, regression-risk assessment, deployment/rollback instructions.`;}
  function initVoice(input,target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){if(target==='teacher')el('voiceStatus').textContent='Speech recognition unavailable. Chrome desktop often supports it. Please type instead.';else alert('Voice dictation is unavailable in this browser. Please type the request.');return;}if(target==='teacher'&&recognition){recognition.stop();return;}const r=new SR();r.lang='en-GB';r.interimResults=false;r.maxAlternatives=1;const button=target==='teacher'?el('voiceInput'):el('builderVoice');button.classList.add('recording');if(target==='teacher')el('voiceStatus').textContent='Listening to you...';r.onresult=(event)=>{const spoken=event.results?.[0]?.[0]?.transcript||'';if(target==='teacher'){message(spoken);}else{el('builderRequest').value=(el('builderRequest').value+' '+spoken).trim();}};r.onerror=(event)=>{if(target==='teacher')el('voiceStatus').textContent='Could not understand your voice ('+event.error+'). You can type instead.';else alert('Dictation failed: '+event.error);};r.onend=()=>{button.classList.remove('recording');if(target==='teacher'){recognition=null;if(!el('voiceStatus').textContent.includes('Could not'))el('voiceStatus').textContent='You can talk or type to your tutor.';}};if(target==='teacher')recognition=r;try{r.start();}catch(e){button.classList.remove('recording');}}
  function pitchDetected(p){if(!p){el('pitchLine').textContent='Listening... play one string';return;}const midi=Math.round(M.freqToMidi(p.frequency));const name=M.midiToName(midi);el('pitchLine').textContent='Detected: '+name+' · approx. '+Math.round(p.frequency)+' Hz';if(lesson().kind!=='melody'||demoRunning||backingOn)return;const target=M.stepMidis(lesson().steps[currentStep],state.capo)[0];const diff=Math.abs(M.freqToMidi(p.frequency)-target);const now=Date.now();if(now-lastPitchAt<900)return;lastPitchAt=now;if(diff<.55){missed=0;if(lastSuccess!==''+currentStep){lastSuccess=''+currentStep;el('listenDetails').textContent='That note sounds close! Nice work. Select the next note when you’re ready.';}}else{missed++;if(missed>=3&&state.prefs.autoHints&&el('hintPanel').classList.contains('hidden')){showHints('auto');missed=0;}}}
  async function toggleMic(){if(A.hasMic()){A.stopMic();el('listenToggle').textContent='Start listening';el('listenHeading').textContent='Ready when you are';el('pitchLine').textContent='No note detected';return;}try{await A.startMic(pitchDetected);el('listenToggle').textContent='■ Stop listening';el('listenHeading').textContent='Listening to your guitar';el('listenDetails').textContent='This version identifies individual notes, not full chord accuracy. For best results play one note at a time.';}catch(e){el('listenDetails').textContent='Microphone unavailable: '+e.message+' (use localhost/HTTPS and grant permission).';}}
  // events
  document.querySelectorAll('[data-page]').forEach(button=>button.addEventListener('click',()=>goPage(button.dataset.page)));
  el('playDemo').addEventListener('click',()=>demoRunning?stopDemo():playDemo());
  el('stopDemo').addEventListener('click',()=>stopDemo());
  el('repeatDemo').addEventListener('click',playDemo);
  el('showHints').addEventListener('click',()=>el('hintPanel').classList.contains('hidden')?showHints():hideHints());
  el('hideHints').addEventListener('click',hideHints);
  el('backingToggle').addEventListener('click',()=>toggleBacking());
  el('exerciseSelect').addEventListener('change',e=>{stopDemo();state.lesson=e.target.value;currentStep=0;save();renderStage();tutor(lesson().description);});
  el('capoSelect').addEventListener('change',e=>{state.capo=Number(e.target.value);save();renderStage();});
  el('tempoRange').addEventListener('input',e=>{state.tempo=Number(e.target.value);renderTempo();save();});
  el('sendMessage').addEventListener('click',()=>message(el('messageInput').value));
  el('messageInput').addEventListener('keydown',e=>{if(e.key==='Enter')message(el('messageInput').value);});
  document.querySelectorAll('[data-quick]').forEach(b=>b.addEventListener('click',()=>message(b.dataset.quick)));
  el('voiceInput').addEventListener('click',()=>initVoice(null,'teacher'));
  el('voiceToggle').addEventListener('click',()=>{state.prefs.speak=!state.prefs.speak;renderPrefs();save();if(!state.prefs.speak&&window.speechSynthesis)speechSynthesis.cancel();});
  el('listenToggle').addEventListener('click',toggleMic);
  el('explanationLength').addEventListener('change',e=>{state.prefs.explanation=e.target.value;save();});
  el('teachingPace').addEventListener('change',e=>{state.prefs.pace=e.target.value;save();});
  el('autoHints').addEventListener('change',e=>{state.prefs.autoHints=e.target.checked;save();});
  el('speakReplies').addEventListener('change',e=>{state.prefs.speak=e.target.checked;renderPrefs();save();});
  el('resetPrefs').addEventListener('click',()=>{state.prefs={...DEFAULT.prefs};renderPrefs();save();});
  el('exportProfile').addEventListener('click',()=>exportJSON('fretwise-learning-profile.json',{instrument:'Yamaha F310',known_chords:['Am','E','Em','D','Dm','Fmaj7','C','G (developing)','A (developing)'],capo:state.capo,knowledge:state.knowledge,preferences:state.prefs,statistics:state.stats}));
  el('builderVoice').addEventListener('click',()=>initVoice(null,'builder'));
  el('saveRequest').addEventListener('click',()=>{const t=el('builderRequest').value.trim();if(!t){alert('Please describe a change first.');return;}state.changes.push({text:t,date:new Date().toISOString()});el('builderRequest').value='';save();renderChanges();});
  el('copyChangeBrief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(changeBrief());el('copyChangeBrief').textContent='✓ Copied for Claude';setTimeout(()=>el('copyChangeBrief').textContent='Copy Claude change brief',2400);}catch(e){alert('Copy unavailable in this browser. Use Download changes instead.');}});
  el('downloadChanges').addEventListener('click',()=>exportJSON('fretwise-change-requests.json',{requests:state.changes,brief:changeBrief()}));
  el('guitarUpload').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/'))return alert('Select an image file.');const image=new Image();const url=URL.createObjectURL(file);image.onload=()=>{const canvas=document.createElement('canvas'),max=900,scale=Math.min(1,max/Math.max(image.width,image.height));canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);state.imageData=canvas.toDataURL('image/jpeg',.68);el('guitarReference').src=state.imageData;URL.revokeObjectURL(url);save();};image.src=url;});
  el('lessonImport').addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>200000)throw Error('Limit imports to 200 KB.');const imported=M.validateImportedExercise(JSON.parse(await file.text()));state.importedLessons.push(imported);state.lesson=imported.id;currentStep=0;selectOptions();save();renderStage();tutor('Your arrangement is loaded. I can demonstrate its sections with the virtual guitar. Check that the notes are correct and that you have permission to use the arrangement.');}catch(err){alert('Could not import lesson: '+err.message);}e.target.value='';});
  window.addEventListener('hashchange',()=>{const v=location.hash.slice(1);if(['studio','teacher','guitar','progress','builder'].includes(v))goPage(v);});
  window.addEventListener('pagehide',()=>{A.stopBacking();A.stopMic();});
  // boot
  if(!lessons().some(l=>l.id===state.lesson))state.lesson='capo';
  state.messages.forEach(m=>addBubble(m.kind,m.text,false));if(!state.messages.length)addBubble('tutor','Hey! I’m Fret, your guitar coach. I know you’re using a Yamaha F310 and working on chord changes and Sultans of Swing. I’ll demonstrate on my guitar first. If something’s confusing, just tell me — I’ll slow down and change how I explain it.',false);
  initWood();selectOptions();el('capoSelect').value=String(state.capo);renderTempo();renderStage();renderPrefs();renderMemory();renderChanges();updateStats();if(state.imageData)el('guitarReference').src=state.imageData;const initial=location.hash.slice(1);goPage(['studio','teacher','guitar','progress','builder'].includes(initial)?initial:'studio');save();
  window.FretwiseDebug={state,lesson,playDemo,stopDemo,detectPitch:A.detectPitch};
})();
