/* Fast unit checks (no browser): music data, the canonical performance timeline, and the tutor brain.
   Run: node test.cjs     Browser journeys: node tests/browser.mjs */
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{},console,Math,Float32Array,Date,setInterval,clearInterval,setTimeout,clearTimeout};
vm.createContext(context);
for(const f of ['music.js','performance.js','audio.js','tutor.js'])vm.runInContext(fs.readFileSync(__dirname+'/'+f,'utf8'),context,{filename:f});
const M=context.window.FRETWISE_MUSIC,A=context.window.FRETWISE_AUDIO,P=context.window.FRETWISE_PERFORMANCE,T=context.window.FRETWISE_TUTOR;
let passed=0,total=0;function test(name,fn){total++;try{fn();passed++;console.log('PASS '+name);}catch(e){console.error('FAIL '+name+': '+e.message);process.exitCode=1;}}
function midiName(n){return M.midiToName(n)}
// Values built inside the vm context carry its own Array/Object prototypes; normalise before deep comparison.
const plain=x=>JSON.parse(JSON.stringify(x));

/* ---- music data (original 0.1 checks, kept) ---- */
test('known chord sound for capo 5',()=>{assert.equal(M.chordSound('Am',5),'Dm');assert.equal(M.chordSound('G',5),'C');assert.equal(M.chordSound('C',5),'F');assert.equal(M.chordSound('Fmaj7',5),'Bbmaj7');});
test('capo sounding names use display names, never internal ids',()=>{assert.equal(M.chordSound('Fmini',5),'Bb (mini barre)');assert.equal(M.chordSound('Fsmall',3),'Ab (3 strings)');assert.equal(M.chordSound('Am',0),'Am');});
test('capo moves every sounding note by 5 semitones',()=>{const a=M.stepMidis({chord:'Am'},0),b=M.stepMidis({chord:'Am'},5);assert.equal(a.length,b.length);a.forEach((n,i)=>assert.equal(b[i]-n,5));});
test('A minor open chord pitch set is A E A C E',()=>{assert.deepEqual([...M.stepMidis({chord:'Am'},0)].map(n=>midiName(n)),['A2','E3','A3','C4','E4']);});
test('F shape progression is defined and musically consistent',()=>{for(const key of ['Fmaj7','Fsmall','Fmini','F'])assert(M.CHORDS[key]);assert.equal(M.stepMidis({chord:'Fsmall'},0).length,3);assert.equal(M.stepMidis({chord:'Fmini'},0).length,4);});
test('every chord voicing matches its name (pitch classes)',()=>{const want={Am:['A','C','E'],A:['A','C♯','E'],E:['E','G♯','B'],Em:['E','G','B'],D:['D','F♯','A'],Dm:['D','F','A'],C:['C','E','G'],G:['G','B','D'],Fmaj7:['F','A','C','E'],Fsmall:['F','A','C'],Fmini:['F','A','C'],F:['F','A','C']};for(const [id,pcs] of Object.entries(want)){const got=[...new Set(M.stepMidis({chord:id},0).map(n=>midiName(n).replace(/-?\d+$/,'')))].sort();assert.deepEqual(got,[...pcs].sort(),id+' voicing wrong: '+got);}});
test('every fretted string in a chord has a finger and fingers are 1–4',()=>{for(const [id,c] of Object.entries(M.CHORDS)){c.frets.forEach((f,s)=>{if(f>0)assert(c.fingers[s]>=1&&c.fingers[s]<=4,id+' string '+s+' has no finger');else assert.equal(c.fingers[s],0,id+' open/muted string has a finger');});}});
test('barres are detected only where finger 1 lies across a fret',()=>{assert.deepEqual({...M.barreFor(M.CHORDS.F.frets,M.CHORDS.F.fingers)},{fret:1,from:0,to:5});assert.deepEqual({...M.barreFor(M.CHORDS.Fmini.frets,M.CHORDS.Fmini.fingers)},{fret:1,from:4,to:5});assert.equal(M.barreFor(M.CHORDS.Am.frets,M.CHORDS.Am.fingers),null);});
test('step frets and solo notes use high e string index 5',()=>{assert.deepEqual([...M.stepFrets({string:5,fret:3})],[-1,-1,-1,-1,-1,3]);assert.equal(M.midiToName(M.stepMidis({string:5,fret:3},0)[0]),'G4');});
test('pitch detector estimates clean 440Hz single note',()=>{const r=44100,n=4096,x=new Float32Array(n);for(let i=0;i<n;i++)x[i]=.24*Math.sin(2*Math.PI*440*i/r);const hit=A.detectPitch(x,r);assert(hit,'pitch estimator returned no pitch');const rounded=Math.round(M.freqToMidi(hit.frequency));assert.equal(rounded,69,'expected A4, got '+hit.frequency);});
test('pitch detector finds low E (82 Hz) without an octave error',()=>{const r=44100,n=4096,x=new Float32Array(n),f=82.41;for(let i=0;i<n;i++)x[i]=.2*Math.sin(2*Math.PI*f*i/r)+.1*Math.sin(2*Math.PI*2*f*i/r)+.05*Math.sin(2*Math.PI*3*f*i/r);const hit=A.detectPitch(x,r);assert(hit);assert.equal(Math.round(M.freqToMidi(hit.frequency)),40);});
test('pitch detector returns no note on silence',()=>{assert.equal(A.detectPitch(new Float32Array(4096),44100),null);});
test('import rejects invalid strings, oversized lessons and unknown chords',()=>{assert.throws(()=>M.validateImportedExercise({kind:'melody',steps:[{string:8,fret:2}]}));assert.throws(()=>M.validateImportedExercise({kind:'chord',steps:[{chord:'Nonsense'}]}));assert.throws(()=>M.validateImportedExercise({kind:'chord',steps:Array.from({length:129},()=>({chord:'Am'}))}));});
test('import validates sections, techniques, beats and fingers',()=>{assert.throws(()=>M.validateImportedExercise({kind:'melody',steps:[{string:5,fret:1}],sections:[{from:0,to:3}]}));assert.throws(()=>M.validateImportedExercise({kind:'melody',steps:[{string:5,fret:1,technique:'tapping'}]}));assert.throws(()=>M.validateImportedExercise({kind:'melody',steps:[{string:5,fret:1,beats:20}]}));const ok=M.validateImportedExercise({kind:'melody',tempo:90,steps:[{string:5,fret:1,finger:1},{technique:'rest',beats:.5},{string:5,fret:3,technique:'hammer'}],sections:[{name:'Start',from:0,to:1}]});assert.equal(ok.steps[1].technique,'rest');assert.equal(ok.sections[0].name,'Start');assert.equal(ok.tempo,90);});
test('original user-authorised exercise import succeeds',()=>{const json=JSON.parse(fs.readFileSync(__dirname+'/sample_original_lesson.json','utf8'));const exercise=M.validateImportedExercise(json);assert.equal(exercise.kind,'melody');assert.equal(exercise.steps.length,4);});
test('all built-in lessons are structured, original and have sections',()=>{assert.equal(M.LESSONS.length,4);for(const l of M.LESSONS){assert(l.steps.length>=4);assert(l.sections.length>=2);assert(/original|build|gentle|exercise/i.test(l.description));}});
test('lessons without sections get phrase-sized auto sections',()=>{const s=M.sectionsFor({steps:new Array(5).fill({chord:'Am'})});assert.deepEqual(plain(s.map(x=>[x.from,x.to])),[[0,1],[2,3],[4,4]]);});

/* ---- canonical performance timeline ---- */
test('timeline: audio events, hand steps and capo all come from one compile',()=>{const p=P.compile(M.LESSONS[0],{capo:5,tempo:120});assert.equal(p.duration,8);for(const e of p.events){const step=p.steps.find(s=>s.index===e.step);assert.equal(step.shape.frets[e.string],e.fret,'event fret disagrees with hand shape');assert.equal(e.midi,M.STRING_MIDI[e.string]+e.fret+5,'event pitch not capo-transposed');assert(e.t>=step.t&&e.t<step.t+step.dur,'event outside its step');}});
test('timeline: downstrokes go low→high, upstrokes high→low over the top strings',()=>{const p=P.compile(M.LESSONS[0],{capo:0,tempo:60});const first=p.events.filter(e=>e.gesture===0).map(e=>e.string);assert.deepEqual(plain(first),[1,2,3,4,5]);const up=p.gestures.find(g=>g.stroke==='U');const upStrings=p.events.filter(e=>e.gesture===p.gestures.indexOf(up)).map(e=>e.string);assert.deepEqual(plain(upStrings),[5,4,3,2]);});
test('timeline: muted strings never sound',()=>{const p=P.compile(M.LESSONS[2],{capo:0,tempo:90});for(const e of p.events){const shape=p.steps.find(s=>s.index===e.step).shape;assert(shape.frets[e.string]>=0);}});
test('timeline: section compile keeps absolute step indexes and starts at t=0',()=>{const p=P.compile(M.LESSONS[0],{capo:5,tempo:120,from:2,to:3});assert.equal(p.steps[0].index,2);assert.equal(p.steps[0].t,0);assert.equal(p.duration,4);assert.equal(p.stepAt(0).index,2);assert.equal(p.stepAt(2.1).index,3);});
test('timeline: tempo halves duration exactly, pitches unchanged',()=>{const a=P.compile(M.LESSONS[3],{capo:0,tempo:60}),b=P.compile(M.LESSONS[3],{capo:0,tempo:120});assert.equal(a.duration,2*b.duration);assert.deepEqual(a.events.map(e=>e.midi),b.events.map(e=>e.midi));});
test('timeline: lead lick uses one hand position (fret 3 = finger 1, fret 5 = finger 3)',()=>{const p=P.compile(M.LESSONS[3],{capo:0,tempo:60});assert.deepEqual(plain(p.events.map(e=>e.finger)),[0,1,3,1]);assert(p.steps.every(s=>s.window===3));});
test('timeline: rests and legato are respected',()=>{const l={id:'x',kind:'melody',steps:[{string:5,fret:3},{technique:'rest'},{string:5,fret:5,technique:'hammer'}]};const p=P.compile(l,{capo:0,tempo:60});assert.equal(p.events.length,2);assert.equal(p.events[1].stroke,null);assert.equal(p.events[1].t,2);});

/* ---- tutor brain ---- */
function brainFor(lessonIdx=0,over={}){const memory=T.defaultMemory();const ctx={lesson:M.LESSONS[lessonIdx],lessons:M.LESSONS,memory,cursor:0,selection:{from:0,to:1},capo:5,tempo:86,baseTempo:86,micOn:false,hintsVisible:false,playing:false,...over};const b=T.create({music:M,getContext:()=>ctx});return {b,ctx};}
const sentences=s=>(s.match(/[^.!?]+[.!?]+/g)||[s]).length;
test('tutor: "overwhelming" switches to one-step mode and stores a teaching preference',()=>{const {b,ctx}=brainFor();ctx.memory.teaching.explanation='detailed';const r=b.handle('This explanation is overwhelming; just one step please');assert.equal(r.intent,'pref_short');assert(r.actions.some(a=>a.type==='prefs'&&a.explanation==='short'));assert(r.remember.some(m=>m.track==='teaching'));});
test('tutor: short mode never sends more than two sentences',()=>{const {b}=brainFor();for(const q of ['How do I play G?','what is the strumming pattern','that was tricky','I can\'t make the barre chord ring','teach me the Sultans of Swing solo','my hand hurts','next','explain that in plain English','how do I change chords smoothly']){const r=b.handle(q);assert(sentences(r.say)<=2,q+' → '+r.say);}});
test('tutor: barre help starts at Fmaj7 and demonstrates it',()=>{const {b}=brainFor();const r=b.handle("I can't make the barre chord ring, my fingers won't stretch");assert(/Fmaj7/.test(r.say));assert.deepEqual(plain(r.actions.map(a=>a.type)),['lesson','select','play','prompt_attempt']);assert.equal(r.actions[0].id,'barre');assert.equal(r.actions[2].from,0);});
test('tutor: dots appear only when asked, and hide on request',()=>{const {b}=brainFor();assert(!b.handle('play it again').actions.some(a=>a.type==='hints'&&a.show));assert(b.handle('Which finger was that? Show me the dots.').actions.some(a=>a.type==='hints'&&a.show));assert(b.handle('hide the dots').actions.some(a=>a.type==='hints'&&!a.show));});
test('tutor: never invents a commercial song; plays nothing',()=>{const {b}=brainFor();for(const q of ['Play the Sultans of Swing intro lick','teach me the Dire Straits solo','play the real song']){const r=b.handle(q);assert.equal(r.intent,'song',q);assert.equal(r.actions.length,0);assert(r.honest);}});
test('tutor: software requests go to Owner Mode, never into teaching memory',()=>{const {b}=brainFor();const r=b.handle('Add a loop-last-four-notes button to the app');assert.equal(r.intent,'owner_change');assert.equal(r.actions[0].type,'owner_request');assert.equal(r.remember.length,0);});
test('tutor: pain stops playback and never encourages playing through it',()=>{const {b}=brainFor();const r=b.handle('my fingers hurt');assert.equal(r.intent,'pain');assert(r.actions.some(a=>a.type==='stop'));assert(/never play through pain/i.test(r.say));});
test('tutor: section flow asks "is this the part?" and yes plays it with a count-in',()=>{const {b}=brainFor();const r=b.handle('section 2');assert(r.actions.some(a=>a.type==='select'&&a.confirm&&a.from===2&&a.to===3));assert(/is this the part/i.test(r.say));const y=b.handle('yes');assert(y.actions.some(a=>a.type==='play'&&a.countIn));});
test('tutor: "no, wrong part" lets the learner move earlier/later',()=>{const {b,ctx}=brainFor();b.handle('section 2');ctx.selection={from:2,to:3};const n=b.handle('no');assert(/earlier|later/i.test(n.say));const e=b.handle('earlier');assert(e.actions.some(a=>a.type==='select'&&a.from===0&&a.to===1));});
test('tutor: repeated difficulty rotates one correction at a time, then offers dots',()=>{const {b}=brainFor();const a=b.handle('that was tricky');const c=b.handle('still tricky');const d=b.handle('I keep missing it');assert(a.actions.some(x=>x.type==='tempo'));assert(c.actions.some(x=>x.type==='play'&&x.loop===3));assert(/diagram/i.test(d.say));assert(!d.actions.some(x=>x.type==='hints'&&x.show),'dots forced without consent');assert(b.handle('yes').actions.some(x=>x.type==='hints'&&x.show));});
test('tutor: mic observation compares single notes honestly and never grades chords',()=>{const {b}=brainFor(3,{selection:{from:0,to:1}});const miss=b.event('attempt',{expected:[{midi:64,label:'E4',step:0},{midi:67,label:'G4',step:1}],heard:[64,65]});assert(/Note 2 should be G4/.test(miss.say)&&/2 frets low/.test(miss.say));const {b:b2}=brainFor(0);const chord=b2.event('attempt',{expected:[],heard:[57]});assert(/can.t judge a full chord/i.test(chord.say));});
test('tutor: action sanitiser drops unknown types and out-of-range values',()=>{const out=T.sanitiseActions([{type:'eval',code:'alert(1)'},{type:'play',from:0,to:99},{type:'tempo',bpm:900},{type:'page',id:'admin'},{type:'play',from:1,to:2,loop:'infinite'},{type:'capo',fret:3}],{lesson:M.LESSONS[0]});assert.deepEqual(plain(out.map(a=>a.type)),['play','capo']);assert.equal(out[0].loop,Infinity);});
test('memory: v0.1 profile migrates without losing notes, prefs or change requests',()=>{const v1={capo:3,prefs:{explanation:'detailed',speak:false},knowledge:['Advanced beginner: knows Am, E, Em, D, Dm, Fmaj7, C; working on G and A.','My action is high at the 5th fret','Prefer just one short instruction, followed by a demonstration and time to try.'],changes:[{text:'Add loop',date:'2026-01-01'}],stats:{sessions:4}};const s=T.migrate(v1);assert.equal(s.memory.version,2);assert.equal(s.memory.teaching.explanation,'detailed');assert.equal(s.memory.teaching.speak,false);assert(s.memory.playing.notes.includes('My action is high at the 5th fret'));assert(s.memory.teaching.notes.some(n=>/one short instruction/.test(n)));assert.equal(s.memory.owner.changes[0].status,'queued');assert.equal(s.stats.sessions,4);assert.equal(T.migrate(s),s,'migration is not idempotent');});

console.log(`\n${passed}/${total} checks passed`);
